apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fibkubcalc-tls
spec:
  secretName: fibkubcalc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibkubcalc.tk
  dnsNames:
    - fibkubcalc.tk
    - www.fibkubcalc.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fibkubcalc.tk
          - www.fibkubcalc.tk
